apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-jobs
spec:
  ttlSecondsAfterFinished: 0
  template:
    spec:
      containers:
        - name: migrate-django
          image: elzig1999/django_app:latest
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: django-app-configmap
          command: [ "python",  "manage.py", "makemigrations", "--noinput" ]
      restartPolicy: Never
  backoffLimit: 2