apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-jobs
  labels:
    app: django-app
    env: dev
spec:
  ttlSecondsAfterFinished: 10
  template:
    spec:
      containers:
        - name: migrate-django
          image: elzig1999/django_app:latest
          imagePullPolicy: Never
          envFrom:
            - secretRef:
                name: django-app-secret
          command: [ "python",  "manage.py", "makemigrations", "--noinput" ]
      restartPolicy: Never
  backoffLimit: 2