apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: nginx-service
    app.kubernetes.io/name: nginx
spec:
  ports:
  - nodePort: 30281
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app.kubernetes.io/name: nginx
  type: NodePort