apiVersion: v1
kind: Service
metadata:
  name: django-service
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: django-service
    app.kubernetes.io/name: django
spec:
  ports:
  - nodePort: 30281
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: django-app
    env: prod
  type: NodePort