apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels:
    app: nginx
    env: zig
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      env: zig
  template:
    metadata:
      labels:
        app: nginx
        env: zig
    spec:
      containers:
      - image: nginx:1.14.2
        name: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  ports:
  - nodePort: 31331
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
    env: zig
  type: NodePort